import nightOwl from 'prism-react-renderer/themes/nightOwl'

export default {
  root: {
    fontFamily: 'body',
    lineHeight: 'body',
    fontWeight: 'body',
  },
  a: {
    color: 'primary',
    textDecoration: 'none',
    ':hover': {
      textDecoration: 'underline',
    },
  },
  h1: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 1,
    fontSize: 6,
    mt: 2,
  },
  h2: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 1,
    fontSize: 5,
    mt: 2,
  },
  h3: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 1,
    fontSize: 4,
    mt: 3,
  },
  h4: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 1,
    fontSize: 3,
  },
  h5: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 1,
    fontSize: 2,
  },
  h6: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 2,
    fontSize: 1,
  },
  code: {
    fontFamily: 'monospace',
    color: 'secondary',
    fontSize: 0,
  },
  inlineCode: {
    fontFamily: 'monospace',
    color: 'secondary',
    bg: 'purple.2',
  },
  pre: {
    variant: 'prism',
    fontFamily: 'monospace',
    fontSize: 0,
    p: 3,
    color: 'text',
    bg: 'muted',
    overflow: 'auto',
    code: {
      color: 'inherit',
    },
  },
  hr: {
    bg: 'muted',
    border: 0,
    height: '1px',
    m: 3,
  },
  CodeBlock: {
    overflow: `auto`,
    mx: '-24px',
    pre: {
      backgroundColor: `transparent`,
      float: `left`,
      minWidth: `100%`,
      margin: 0,
      px: '24px',
      py: '12px',
      borderRadius: '10px',
    },
    highlightLine: {
      backgroundColor: `#45474e`,
      borderLeftColor: `#49d0c5`,
      borderLeftStyle: `solid`,
      borderLeftWidth: `0.25em`,
      display: `block`,
      marginRight: `-1em`,
      marginLeft: `-1em`,
      paddingRight: `1em`,
      paddingLeft: `0.75em`,
    },
    title: {
      fontFamily: `mono`,
      backgroundColor: nightOwl.plain.backgroundColor,
      borderBottomWidth: `2px`,
      borderBottomStyle: `solid`,
      borderBottomColor: `#f0f0f0`,
      color: nightOwl.plain.color,
      padding: '0.5rem 1rem',
      borderRadius: '10px',
    },
  },
}
