import nightOwl from 'prism-react-renderer/themes/nightOwl'

export default {
  root: {
    fontFamily: 'body',
    lineHeight: 'body',
    fontWeight: 'body',
  },
  a: {
    color: 'primary',
    textDecoration: 'underline',
    ':hover': {
      textDecoration: 'none',
    },
  },
  h1: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mt: 7,
    mb: 4,
    fontSize: 7,
  },
  h2: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 4,
    mt: 7,
    fontSize: 6,
  },
  h3: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 4,
    mt: 7,
    fontSize: 5,
  },
  h4: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 4,
    mt: 7,
    fontSize: 4,
  },
  h5: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 4,
    mt: 7,
    fontSize: 3,
  },
  h6: {
    fontFamily: 'heading',
    fontWeight: 'heading',
    lineHeight: 'heading',
    m: 0,
    mb: 4,
    mt: 7,
    fontSize: 2,
  },
  p: {
    m: 0,
    mb: 5,
  },
  blockquote: {
    ml: -5,
    fontFamily: 'serif',
    fontSize: 3,
    borderLeft: (theme) => `4px solid ${theme.colors.primary}`,
    '& > p': {
      lineHeight: 'relaxed',
      pl: 5,
    },
  },
  code: {
    fontFamily: 'monospace',
    color: 'secondary',
    fontSize: 0,
  },
  inlineCode: {
    fontFamily: 'monospace',
    color: 'text',
    bg: 'green.1',
    px: 1,
    borderRadius: 4,
    fontSize: 1,
  },
  pre: {
    variant: 'prism',
    fontFamily: 'monospace',
    fontSize: 1,
    color: 'text',
    bg: 'muted',
    overflow: 'auto',
    code: {
      color: 'inherit',
    },
  },
  hr: {
    bg: 'green.1',
    border: 0,
    height: '1px',
    m: 3,
  },
  CodeBlock: {
    overflow: `auto`,
    mx: -5,
    mb: 5,
    boxShadow: '0 10px 20px rgba(0,0,0,.15), 0 3px 6px rgba(0,0,0,.10)',
    borderRadius: 'md',
    pre: {
      backgroundColor: `transparent`,
      float: `left`,
      minWidth: `100%`,
      margin: 0,
      px: 5,
      py: 3,
      borderRadius: [null, 'md'],
    },
    highlightLine: {
      backgroundColor: 'hsl(197, 95%, 15%)',
      borderLeftColor: `green.2`,
      borderLeftStyle: `solid`,
      borderLeftWidth: `0.25em`,
      display: `block`,
      marginRight: -5,
      ml: -5,
      paddingRight: `1em`,
      paddingLeft: `0.75em`,
    },
    title: {
      fontFamily: `mono`,
      backgroundColor: nightOwl.plain.backgroundColor,
      borderBottomWidth: `2px`,
      borderBottomStyle: `solid`,
      borderBottomColor: `#f0f0f0`,
      color: nightOwl.plain.color,
      mx: -5,
      px: 5,
      pt: 3,
      pb: 1,
      mb: -2,
      borderRadius: 'md',
    },
  },
}
